name: Workflow deploy for azure-app-service

on:
  push:
    branches:
      - azure-deploy-test

env:
  MY_SECRET: ${{ secrets.TEST_SECRET }}
  ENVIROMENT: ${{ secrets.ENVIROMENT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.1'

      - name: Instala dependencias (limpio)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Construye la app
        run: npm run build

      - name: Despliega en Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: actions-test
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: './dist'
