name: Workflow deploy for azure-app-service

on:
  push:
    branches:
      - azure-deploy-test

env:
  MY_SECRET: ${{ secrets.TEST_SECRET }}
  ENVIROMENT: ${{ secrets.ENVIROMENT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Building web app
        uses: azure/appservice-build@v3
        with:
          platform: "node"
          node_version: 22.15.1
          source_directory: "."
          output-directory: "dist"

      - name: Deploying web app to azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: actions-test
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
